Development
Mikkko/ruby_codebreaker_gem pull request #1
Opened 2020-07-19 13:27 UTC by Mikkko

2020-07-24 16:27 UTC, Dimasfullxq requested changes

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/difficulty.rb
> +      validate(difficulty)
I think you should remove validation from constructor.

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/game.rb
> +    WIN_COMBINATION = '++++'.freeze
Imho, markers should be in console.

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/game.rb
> +    def self.show_statistic(file)
It would be cool if game manage only game logic. Move this method to extend service.

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/game.rb
> +    def save_result(file)
The same as above. For this logic, you will create extend object in console. Just move this method to your Statistic class.

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/player.rb
> +      validate(name)
The same with validation in constructor.

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/guess.rb
> +    WRONG_ANSWER_SYMBOL = '-'.freeze
Move it to console, like markers. Lets make gem to return only count of 'plus', 'minus, 'empty' checks. Console/web will be adapting this in markers. Its gonna be great!

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/guess.rb
> +      validate_guess(guess)
Validation in constructor.

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/statistic.rb
> +    def sort_stats
Are u sure it work correct, I think each next sorting will resort previous one.

2020-07-24 16:27 UTC, Dimasfullxq commented on lib/codebreaker/classes/statistic.rb
> +      File.file?(@file_path) ? YAML.load_file(@file_path) : raise(StatisticFileError)
What will be if file exists, but it's empty?

2020-07-25 08:51 UTC, artem247 commented on lib/codebreaker/classes/statistic.rb
> +    def sort_stats
@Dimasfullxq 
sort_by can accepts multiple parameters for one sort. The tricky part is that they all should be in the same direction (asc/dec)

2020-07-25 11:57 UTC, DaniilYusha requested changes

2020-07-25 11:57 UTC, DaniilYusha commented on lib/codebreaker.rb
> +require_relative 'codebreaker/errors/wrong_argument_error'
nit: group your requires like:
`require_relative 'codebreaker/errors/statistic_file_error'
require_relative 'codebreaker/errors/difficulty_error'

require_relative 'codebreaker/modules/validator'

require_relative 'codebreaker/classes/difficulty'
require_relative 'codebreaker/classes/player'`
It makes this file more readable

2020-07-25 11:57 UTC, DaniilYusha commented on spec/codebreaker/difficulty_spec.rb
> +    it 'raise DifficultyError if given unknown difficulty' do
nit: I think it will be better to use `context` in such situations. For example:
`context 'when given unknown difficulty' do`
    `it 'raises DifficultyError' do`
        ...
    `end`
`end`
P.s.: best practice

2020-07-25 11:57 UTC, DaniilYusha commented on spec/codebreaker/difficulty_spec.rb
> +  describe '.attempts' do
Please use `.` symbol for testing class' methods (like initialize), but here should use `#`

2020-07-25 11:57 UTC, DaniilYusha commented on spec/codebreaker/difficulty_spec.rb
> +  describe '.hints' do
same

2020-07-25 11:57 UTC, DaniilYusha commented on spec/codebreaker/game_guess_spec.rb
> +  describe 'guess' do
please use `#` for instance methods

2020-07-25 11:57 UTC, DaniilYusha commented on spec/codebreaker/game_hint_spec.rb
> +    it 'raise HintError if hints are absent' do
nit: the same as about using `context`

2020-07-27 14:11 UTC, Mikkko commented on lib/codebreaker.rb
> +require_relative 'codebreaker/errors/wrong_argument_error'
done :)

2020-07-27 14:17 UTC, Mikkko commented on lib/codebreaker/classes/statistic.rb
> +      File.file?(@file_path) ? YAML.load_file(@file_path) : raise(StatisticFileError)
this cannot happen unless user adds empty file himself

2020-07-27 15:06 UTC, Mikkko commented on lib/codebreaker/classes/difficulty.rb
> +      validate(difficulty)
done!

2020-07-27 15:06 UTC, Mikkko commented on lib/codebreaker/classes/guess.rb
> +      validate_guess(guess)
removed!

2020-07-27 15:06 UTC, Mikkko commented on lib/codebreaker/classes/player.rb
> +      validate(name)
removed!

2020-07-27 15:08 UTC, Mikkko commented on lib/codebreaker/classes/game.rb
> +    def save_result(file)
removed!

2020-07-27 15:08 UTC, Mikkko commented on lib/codebreaker/classes/game.rb
> +    def self.show_statistic(file)
removed!

2020-07-28 11:23 UTC, Mikkko commented on lib/codebreaker/classes/guess.rb
> +    WRONG_ANSWER_SYMBOL = '-'.freeze
made function to change symbols

2020-07-28 11:23 UTC, Mikkko commented on spec/codebreaker/difficulty_spec.rb
> +    it 'raise DifficultyError if given unknown difficulty' do
made

2020-07-28 11:23 UTC, Mikkko commented on spec/codebreaker/game_hint_spec.rb
> +    it 'raise HintError if hints are absent' do
done

2020-07-28 11:26 UTC, katiakub approved these changes

2020-07-28 12:42 UTC, Dimasfullxq approved these changes

2020-07-28 14:04 UTC, artem247 approved these changes
Neat.

2020-07-28 14:24 UTC, DaniilYusha approved these changes

2020-07-29 15:02 UTC, Svatok approved these changes

2020-07-29 16:16 UTC, merged